@startuml

!include <C4/C4_Container>
!include <cloudinsight/kafka>

SHOW_PERSON_PORTRAIT()

title Football Team Diagram - $Team.name

Container($Team.id,"$Team.name","Punti:$Team.point","Budget:$BudgetTeam")

#foreach($player in $Players)
    Person($player.id,"$player.name","Maglia:$player.numberShirt")
    Rel($player.id,$Team.id,"play")
#end

#foreach($champ in $Championship)
    System_Ext($champ.id,"$champ.name","Campionato")
    Rel($champ.id,$Team.id,"Championship appartenent")
#end

@enduml